language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env:
        - CXX=g++-4.9
        - CX=g++-4.9
        - CC=gcc-4.9

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['clang-3.4', 'g++-4.8']
      env:
        - CXX=clang++
        - CX=clang++
        - CC=clang

install:
  - $CX --version

before_script:
  - sudo apt-get -qq install libgtest-dev
  - pushd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - popd

script:
  - cd ./build && make bits=64
  - for filename in $( ls ./bin/release/$CC); do ./bin/release/$CC/$filename; done

notifications:
  slack:
    on_success: never
    on_failure: never
