language: cpp

compiler: 
  - clang++

addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.7

install:
  - ls -l /usr/bin
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - export CX=$CXX
  - $CX --version

before_script:
  - sudo apt-get -qq install libgtest-dev
  - pushd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - popd

script:
  - cd ./build && make bits=64
  - for filename in $( ls ./bin/release/$CC); do ./bin/release/$CC/$filename; done

notifications:
  slack:
    on_success: never
    on_failure: never
